CREATE TABLE VIRUS
(COD_VIRUS NUMBER(13) CONSTRAINT PK_COD_VIRUS PRIMARY KEY,
NOME_CIENTIFICO VARCHAR2(100),
NOME_POPULAR VARCHAR2(100),
PERIODO_INCUBACAO DATE);

CREATE TABLE MEDICAMENTO
(COD_MEDICAMENTO NUMBER(13) CONSTRAINT PK_COD_MEDICAMENTO PRIMARY KEY,
NOME_VENDA VARCHAR2(100),
COMPOSTO_ATIVO VARCHAR2(100));

CREATE TABLE PACIENTE
(COD_TIPO_PACIENTE NUMBER(13) CONSTRAINT PK_COD_TIPO_PACIENTE PRIMARY KEY,
TIPO VARCHAR2(100));

CREATE TABLE COQUETEL
(COD_COQUETEL NUMBER(13) CONSTRAINT PK_COD_COQUETEL PRIMARY KEY);

CREATE TABLE MEDICAMENTO_VIRUS (
COD_MEDICAMENTO NUMBER(13),
COD_VIRUS NUMBER(13),
CONSTRAINT PK_MEDICAMENTO_VIRUS PRIMARY KEY (COD_MEDICAMENTO, COD_VIRUS),
CONSTRAINT FK_MED_VIR_MEDICAMENTO FOREIGN KEY (COD_MEDICAMENTO) REFERENCES MEDICAMENTO(COD_MEDICAMENTO),
CONSTRAINT FK_MED_VIR_VIRUS FOREIGN KEY (COD_VIRUS) REFERENCES VIRUS(COD_VIRUS));

CREATE TABLE TRATAMENTO (
COD_MEDICAMENTO NUMBER(13),
COD_TIPO_PACIENTE NUMBER(13),
DOSAGEM_RECOMENDADA VARCHAR2(100),
CONSTRAINT PK_TRATAMENTO PRIMARY KEY (COD_MEDICAMENTO, COD_TIPO_PACIENTE),
CONSTRAINT FK_TRAT_MEDICAMENTO FOREIGN KEY (COD_MEDICAMENTO) REFERENCES MEDICAMENTO(COD_MEDICAMENTO),
CONSTRAINT FK_TRAT_PACIENTE FOREIGN KEY (COD_TIPO_PACIENTE) REFERENCES PACIENTE(COD_TIPO_PACIENTE));

CREATE TABLE COMPOSICAO_COQUETEL (
COD_COQUETEL NUMBER(13),
COD_MEDICAMENTO NUMBER(13),
CONCENTRACAO NUMBER(5,2),
CONSTRAINT PK_COMPOSICAO_COQUETEL PRIMARY KEY (COD_COQUETEL, COD_MEDICAMENTO),
CONSTRAINT FK_COMP_COQUETEL FOREIGN KEY (COD_COQUETEL) REFERENCES COQUETEL(COD_COQUETEL),
CONSTRAINT FK_COMP_MEDICAMENTO FOREIGN KEY (COD_MEDICAMENTO) REFERENCES MEDICAMENTO(COD_MEDICAMENTO));
