CREATE TABLE MEDICO (
  CRM NUMBER(100) CONSTRAINT pk_CRM PRIMARY KEY,
  NOME VARCHAR2(100),
  TELEFONE VARCHAR2(30),
  ESPECIALIDADE VARCHAR2(50));

CREATE TABLE MAE (
  COD_MAE NUMBER(100) CONSTRAINT pk_COD_MAE PRIMARY KEY,
  NOME VARCHAR2(100),
  ENDERECO VARCHAR2(100),
  TELEFONE VARCHAR2(30),
  DATA_NASC DATE);

CREATE TABLE BEBE (
  COD_BEBE NUMBER(100) CONSTRAINT pk_COD_BEBE PRIMARY KEY,
  NOME VARCHAR2(100),
  DATA_NASC DATE,
  PESO_NASC NUMBER(5,2),
  ALTURA NUMBER(4,1),
  FK_MAE NUMBER(100),
  FK_MEDICO NUMBER(100),
  FOREIGN KEY (FK_MAE) REFERENCES MAE (COD_MAE),
  FOREIGN KEY (FK_MEDICO) REFERENCES MEDICO (CRM));
